# Generated by Django 3.2.9 on 2021-11-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='file_name',
            field=models.FileField(upload_to='plots'),
        ),
        migrations.AlterField(
            model_name='csv',
            name='uploaded',
            field=models.DateTimeField(),
        ),
    ]
